### ISSUE TITLE
Orei 4x4 HDMI Matrix

### ISSUE THREAD

**Issue by nwcrengie** [bitfocus/companion-module-orei-matrix#1]
Support for Orei 4x4 HDMI Matrix

Feature Request: Point to point routing

Documentation:

https://www.orei.com/products/ultrahd-4k-60hz-over-single-cat6-7-cable-with-hdr-switcher

[Orei 4x4 HDMI Matrix Documentation](https://cdn.shopify.com/s/files/1/1988/4253/files/UHD48-EX230-K_User_Manual_V1.0_140x210mm.pdf?v=1620372533)

Thanks!

**Comment by nwcrengie** [comment]
Hey guys I'm finally coming around to needing this module. I've tested the Telnet commands and they are identical to the RS232 commands.

**Comment by jrviz** [comment]
Module completed and tested by OP

**Comment by Mcarey17** [comment]
I am new to companion and this whole community, and I am trying to learn how to set op commands. I have an OREI Matrix, how do I go about using this module? Thank you,

**Comment by josephdadams** [comment]
Download a recent beta build and search for orei.

**Comment by jrviz** [comment]
You need to set up the ip adress for the unit and number of output (4 or 8). There are commands to select the input, switch the outputs and enable/disable HDMI, Cat connections and mute.
![image](https://user-images.githubusercontent.com/11279475/170933293-2c0826f0-e137-4b0f-879c-8b4a555b973c.png)
